###############################################################################
# Nacos分支的配置文件存储在nacos中【包括数据库配置、Redis配置、RabbitMQ等 ..】         #
# 参考 http://www.moguit.cn/#/info?blogUid=8dc52bd61e36fa56cfc7699815375572   #
##############################################################################
spring:
  profiles:
    active: dev